language: node_js
node_js:
  - "0.11"
before_script: #http://badsyntax.co/post/travis-ci-and-bower (these run after npm install)
  - npm install -g bower
  - bower install
after_success:
  - coveralls

